// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC102Gg9k0FO5K9gNvU8fYIwr0_BE0XuQY',
    appId: '1:188928498573:web:1102f6cc2faabc9db73bc4',
    messagingSenderId: '188928498573',
    projectId: 'suqnashmi',
    authDomain: 'suqnashmi.firebaseapp.com',
    storageBucket: 'suqnashmi.appspot.com',
    measurementId: 'G-TJNTH62PZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOjLQT3HTCbMWIFnQ9hGVyH1MgSEJNqbc',
    appId: '1:188928498573:android:0daca204066749dbb73bc4',
    messagingSenderId: '188928498573',
    projectId: 'suqnashmi',
    storageBucket: 'suqnashmi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7n2-4oUuK3NdeS15omiijCB-7kjafiho',
    appId: '1:188928498573:ios:5caab09624d48437b73bc4',
    messagingSenderId: '188928498573',
    projectId: 'suqnashmi',
    storageBucket: 'suqnashmi.appspot.com',
    iosBundleId: 'com.example.nashmiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7n2-4oUuK3NdeS15omiijCB-7kjafiho',
    appId: '1:188928498573:ios:5caab09624d48437b73bc4',
    messagingSenderId: '188928498573',
    projectId: 'suqnashmi',
    storageBucket: 'suqnashmi.appspot.com',
    iosBundleId: 'com.example.nashmiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC102Gg9k0FO5K9gNvU8fYIwr0_BE0XuQY',
    appId: '1:188928498573:web:80548acecb0e73efb73bc4',
    messagingSenderId: '188928498573',
    projectId: 'suqnashmi',
    authDomain: 'suqnashmi.firebaseapp.com',
    storageBucket: 'suqnashmi.appspot.com',
    measurementId: 'G-8F9YF4H6RG',
  );

}